### PR TITLE
Installation instructions

### PR DESCRIPTION
**Pull request by hamelsmu**

### CODE REVIEW

**Comment by mallamanis** [comment]
@mmjb Should we just publish this to pipy?

**Comment by mallamanis** [comment]
@hamelsmu I am setting up a pypi CD pipeline. Will update here.

**Comment by hamelsmu** [comment]
I would really love to learn how to do this using azure pipelines!   If you have any pointers on how I can get started please let me know (docs, etc.)

**Comment by mallamanis** [comment]
@hamelsmu it's now on public pip: https://pypi.org/project/dpu-utils/ could you update the PR to reflect that?

re Azure pipelines, yes: that's the link.

**Pull request merged**
